let var1 = true;
let var2 =["YEISON","DAVID","MORENO NIETO"];
let var3 = 45;
let var4= 7.4;
let var5= "YEISON DAVID MORENO NIETO";
console.log("esto es un:",typeof var1);
console.log("esto es un:",typeof var2);
console.log("esto es un:",typeof var3);
console.log("esto es un:",typeof var4);
console.log("esto es un:",typeof var5);